name: passholder-tracker
region: nyc
services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/passholder-tracker
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npx serve -s dist -l 8080
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /
    static_sites:
      - name: static
        github:
          repo: YOUR_GITHUB_USERNAME/passholder-tracker
          branch: main
          deploy_on_push: true
        build_command: npm install && npm run build
        output_dir: dist
        catchall_document: index.html

